### ISSUE TITLE
Code Pad gets stuck

### ISSUE THREAD

**Issue by roefer** [k-pet-group/BlueJ-Greenfoot#2209]
Code pad has a problem with the new version of instanceof. Type:

    Number n = 1;
    n instanceof Integer i

As a result, code pad does not accept input anymore. Even resetting the VM does not help.

**Comment by neilccbrown** [comment]
It seems that due to this compiler bug https://bugs.openjdk.org/browse/JDK-8278834 the JDK fails compilation without issuing a compiler error, which BlueJ does not expect.  This caused the code pad to get stuck.  I've put a fix in at our end that avoids the issue (plus, the bug is fixed in JDK 19 onwards for the future).

Note that instanceof variable declarations like this will work within the same expression (e.g. `(n instanceof Integer i) ? i.toString() : ""`) but if you just have `n instanceof Integer i` by itself, it will not retain the declared variable for future expressions.
