### ISSUE TITLE
Deb packaging issue

### ISSUE THREAD

**Issue by theofficialgman** [k-pet-group/BlueJ-Greenfoot#2249]
the official deb depends on 
```
 bluej : Depends: openjdk-11-jdk (>= 11) but it is not installable
```

which is not available in debian bookworm and newer versions of debian.
Can the `openjdk-11-jdk (>= 11)` dependency be changed to `java11-sdk` which all java 11 jdk (and newer such as openjdk-17) have as provides? That is all you need to do. You should probably also change `openjdk-17-jdk (>= 17)` to `java17-sdk` while you are at it

https://github.com/k-pet-group/BlueJ-Greenfoot/blob/main/bluej/package/debianfiles/DEBIAN/control
https://github.com/k-pet-group/BlueJ-Greenfoot/blob/main/bluej/package/gfdebianfiles/DEBIAN/control

~~I am not sure about the `libopenjfx-java`. you will likely need to provide that in your deb itself rather than rely on the distro having it available.~~ edit: crossed out since `libopenjfx-java` is available and only is listed since `openjdk-11-jdk` is not installable.

**Comment by neilccbrown** [comment]
Hi,

Looking at the linked issue, does this refer to the Raspberry Pi version?  The files you linked are for the "unbundled" version which we no longer ship.  Our .deb on the main page bundles both OpenJDK and OpenJFX inside because of these issues, so we don't have these dependencies in there:

https://github.com/k-pet-group/BlueJ-Greenfoot/blob/main/bluej/package/debianfiles-bundled/DEBIAN/control

**Comment by theofficialgman** [comment]
Yes I am referring to the version available on piOS. Bookworm is in testing and it does not install due to this issue. Not sure who makes or maintains that package.

**Comment by theofficialgman** [comment]
closing as it was never an issue here. upstream piOS has removed the `bluej` package (it was quite out of date anyway)

shipping an unbundled version officially again would be very much appreciated though. ping me if you ever do that again.
