### ISSUE TITLE
[BLUEJ-435] Line number font size does not change

### ISSUE THREAD

**Issue by neilccbrown** [k-pet-group/BlueJ-Greenfoot#435]
When a user changes the font size of their code the line numbers stay the same size. This can be a problem where code is displayed on projectors as the line numbers become unreadable.

Line numbers should either increase in size relative to the font size, or increase enough to be visible depending on the font size.

---

**Issue metadata**

- Issue type: Task
- Priority: Medium
- Fix versions: 3.1.6

**Comment by PwtKCL** [comment]
The bug can still be observed in 5.1.0 as reported by a user in our support message today.
Maybe the bug was corrected at the time but changes in the editor didn't preserve the changes, or the bug has been closed for another reason? 
I reopen the bug now so we can investigate and take actions in the next updates of BlueJ.
